apply plugin: 'com.android.application'

android {
    namespace 'org.hamidk.divarpushlab'
    compileSdk 34

    defaultConfig {
        applicationId 'org.hamidk.divarpushlab'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0-lab'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
